"""increase resume file type length

Revision ID: 37280f162ff4
Revises: a8e243ddd5b3
Create Date: 2026-10-03 11:23:34.705764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37280f162ff4'
down_revision: Union[str, Sequence[str], None] = 'a8e243ddd5b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=225),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'file_type',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
