"""add screenings

Revision ID: 4ec4cd2162f6
Revises: 6661f71d0b43
Create Date: 2026-10-06 20:12:41.218200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ec4cd2162f6'
down_revision: Union[str, Sequence[str], None] = '6661f71d0b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screenings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('jd_filename', sa.String(length=255), nullable=False),
    sa.Column('jd_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screenings_id'), 'screenings', ['id'], unique=False)
    op.add_column('job_requirements', sa.Column('required_experience_areas', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_requirements', 'required_experience_areas')
    op.drop_index(op.f('ix_screenings_id'), table_name='screenings')
    op.drop_table('screenings')
    # ### end Alembic commands ###
