"""add structured experience requirements

Revision ID: 5b4a857a93f2
Revises: a0dc3d3389cd
Create Date: 2026-10-07 20:26:47.291347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b4a857a93f2'
down_revision: Union[str, Sequence[str], None] = 'a0dc3d3389cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screening_requirements', sa.Column('maximum_experience_years', sa.Integer(), nullable=True))
    op.add_column(
    "screening_requirements",
    sa.Column(
        "experience_requirement_type",
        sa.String(length=50),
        nullable=False,
        server_default="NONE",
    ),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screening_requirements', 'experience_requirement_type')
    op.drop_column('screening_requirements', 'maximum_experience_years')
    # ### end Alembic commands ###
