"""add screening requirements

Revision ID: a0dc3d3389cd
Revises: b40af95f417e
Create Date: 2026-10-06 23:37:00.375569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0dc3d3389cd'
down_revision: Union[str, Sequence[str], None] = 'b40af95f417e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screening_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screening_id', sa.Integer(), nullable=False),
    sa.Column('required_skills', sa.Text(), nullable=True),
    sa.Column('preferred_skills', sa.Text(), nullable=True),
    sa.Column('minimum_experience_years', sa.Integer(), nullable=True),
    sa.Column('required_experience_areas', sa.Text(), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_requirements_id'), 'screening_requirements', ['id'], unique=False)
    op.create_index(op.f('ix_screening_requirements_screening_id'), 'screening_requirements', ['screening_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screening_requirements_screening_id'), table_name='screening_requirements')
    op.drop_index(op.f('ix_screening_requirements_id'), table_name='screening_requirements')
    op.drop_table('screening_requirements')
    # ### end Alembic commands ###
