"""make candidate job optional

Revision ID: b40af95f417e
Revises: fcbd0afe92e9
Create Date: 2026-10-06 20:30:30.027213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b40af95f417e'
down_revision: Union[str, Sequence[str], None] = 'fcbd0afe92e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
