"""link candidates to screenings

Revision ID: fcbd0afe92e9
Revises: 4ec4cd2162f6
Create Date: 2026-10-06 20:28:35.810757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcbd0afe92e9'
down_revision: Union[str, Sequence[str], None] = '4ec4cd2162f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('screening_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_candidates_screening_id'), 'candidates', ['screening_id'], unique=False)
    op.create_foreign_key(None, 'candidates', 'screenings', ['screening_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_index(op.f('ix_candidates_screening_id'), table_name='candidates')
    op.drop_column('candidates', 'screening_id')
    # ### end Alembic commands ###
